
-- Insert Pig TEST
INSERT INTO feed (`id`, `description`, `is_deleted`, `amount`, `code`, `unit`, `feed_type_id`, `herd_id`) VALUES ('1', '1', '0', '100', '1', '1', '1', '1');
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id) values ('Face to face zero tolerance firmware', 'B3', 'Orange', '2019-09-16', 0, '2020-12-19', 'Hampshire', 198, 1, 1, 1);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id) values ('Exclusive full-range structure', 'C2', 'Orange', '2019-10-28', 1, '2020-03-02', 'Meishan', 243, 1, 1, 1);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id) values ('Multi-tiered methodical leverage', 'A2', 'Blue', '2019-04-03', 0, '2020-10-05', 'Landrace', 112, 1, 1, 1);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id) values ('Universal foreground paradigm', 'B2', 'Green', '2019-10-16', 0, '2020-05-23', 'Chester White', 101, 1, 1, 1);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id) values ('Open-source object-oriented firmware', 'C3', 'Khaki', '2019-04-22', 0, '2020-07-27', 'Yorkshire', 229, 1, 1, 1);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id) values ('Managed context-sensitive contingency', 'B1', 'Yellow', '2019-08-03', 1, '2020-10-29', 'Yorkshire', 135, 2, 1, 2);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id) values ('Monitored bottom-line functionalities', 'C1', 'Green', '2019-03-11', 0, '2020-10-27', 'Pietrain', 230, 2, 1, 2);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id) values ('Networked systemic challenge', 'A3', 'Purple', '2019-01-29', 1, '2020-06-26', 'Hampshire', 152, 2, 1, 2);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id) values ('Public-key motivating hub', 'A1', 'Fuscia', '2019-06-28', 1, '2020-02-19', 'Meishan', 71, 2, 1, 2);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id) values ('Programmable explicit monitoring', 'A3', 'Khaki', '2019-07-23', 1, '2020-04-30', 'Landrace', 125, 2, 1, 2);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Customer-focused zero defect access', 'B2', 'Khaki', '2020-02-02', 1, '2020-07-18', 'Hampshire', 56, 3, 1, 3, 1, 2);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Profound next generation database', 'B1', 'Puce', '2020-02-02', 1, '2020-06-16', 'Hampshire', 249, 3, 1, 3, 1, 2);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Decentralized optimizing initiative', 'B3', 'Teal', '2020-02-02', 1, '2020-10-27', 'Hampshire', 208, 3, 1, 3, 1, 2);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Mandatory analyzing success', 'A3', 'Blue', '2020-02-02', 0, '2020-10-08', 'Hampshire', 116, 3, 1, 3, 1, 2);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Progressive encompassing knowledge base', 'C3', 'Teal', '2020-02-02', 1, '2020-08-17', 'Hampshire', 94, 3, 1, 3, 1, 2);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Implemented context-sensitive ability', 'C1', 'Teal', '2020-02-02', 1, '2020-07-30', 'Yorkshire', 94, 4, 1, 4, 6, 5);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Integrated reciprocal ability', 'A2', 'Mauv', '2020-02-02', 0, '2020-10-21', 'Yorkshire', 130, 4, 1, 4, 6, 5);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Pre-emptive bandwidth-monitored Graphic Interface', 'B1', 'Pink', '2020-02-02', 1, '2020-05-17', 'Yorkshire', 88, 4, 1, 4, 6, 5);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Customizable value-added access', 'A3', 'Teal', '2020-02-02', 0, '2020-05-15', 'Yorkshire', 180, 4, 1, 4, 6, 5);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('User-centric incremental product', 'C3', 'Red', '2020-02-02', 0, '2020-07-15', 'Yorkshire', 136, 4, 1, 4, 6, 5);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Multi-layered dynamic analyzer', 'C1', 'Mauv', '2020-04-05', 0, '2021-01-04', 'Landrace', 88, 5, 1, 5, 10, 3);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Intuitive bifurcated data-warehouse', 'A1', 'Aquamarine', '2020-04-05', 1, '2021-01-01', 'Landrace', 108, 5, 1, 5, 10, 3);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Sharable full-range knowledge user', 'C3', 'Fuscia', '2020-04-05', 1, '2021-01-05', 'Landrace', 237, 5, 1, 5, 10, 3);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Automated maximized local area network', 'C3', 'Blue', '2020-04-05', 0, '2021-01-01', 'Landrace', 80, 5, 1, 5, 10, 3);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Mandatory zero defect benchmark', 'A1', 'Pink', '2020-04-05', 1, '2021-01-02', 'Landrace', 82, 5, 1, 5, 10, 3);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Reduced composite structure', 'B3', 'Khaki', '2020-04-05', 1, '2021-01-04', 'Meishan', 239, 7, 1, 7, 2, 7);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Synergized holistic migration', 'A2', 'Violet', '2020-04-05', 1, '2021-01-02', 'Meishan', 182, 7, 1, 7, 2, 7);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Focused multimedia secured line', 'A1', 'Purple', '2020-04-05', 1, '2021-01-03', 'Meishan', 176, 7, 1, 7, 2, 7);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Universal systematic array', 'B1', 'Blue', '2020-04-05', 0, '2021-01-05', 'Pietrain', 226, 7, 1, 7, 2, 7);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Extended directional matrix', 'C2', 'Maroon', '2020-04-05', 0, '2021-01-02', 'Meishan', 89, 7, 1, 7, 2, 7);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Integrated multi-tasking application', 'A2', 'Pink', '2020-10-11', 1, '2022-01-05', 'Yorkshire', 115, 8, 1, 8, 16, 24);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Fully-configurable interactive help-desk', 'A3', 'Blue', '2020-10-11', 1, '2022-01-04', 'Landrace', 157, 8, 1, 8, 16, 24);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Sharable client-driven alliance', 'A1', 'Khaki', '2020-10-11', 1, '2022-01-02', 'Yorkshire', 215, 8, 1, 8, 16, 24);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Automated clear-thinking groupware', 'A1', 'Red', '2020-10-11', 1, '2022-01-01', 'Landrace', 248, 8, 1, 8, 16, 24);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Universal demand-driven data-warehouse', 'B1', 'Green', '2020-10-11', 0, '2022-01-01', 'Yorkshire', 114, 8, 1, 8, 16, 24);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Synergistic bifurcated task-force', 'A1', 'Green', '2020-10-11', 1, '2022-01-04', 'Hampshire', 123, 9, 1, 9, 11, 21);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Automated grid-enabled framework', 'B1', 'Indigo', '2020-10-11', 1, '2022-01-04', 'Hampshire', 173, 9, 1, 9, 11, 21);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Managed incremental Graphical User Interface', 'A3', 'Khaki', '2020-10-11', 0, '2022-01-01', 'Landrace', 85, 9, 1, 9, 11, 21);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Synergistic real-time portal', 'A3', 'Blue', '2020-10-11', 0, '2022-01-05', 'Hampshire', 73, 9, 1, 9, 11, 21);
insert into pig (description, code, color, import_date, gender, export_date, spec, weight, cote_id, feed_id, herd_id, father_id, mother_id) values ('Pre-emptive local synergy', 'B2', 'Aquamarine', '2020-10-11', 0, '2022-01-04', 'Hampshire', 241, 9, 1, 9, 11, 21);







